pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm test
  publish:
    image: plugins/docker
    settings:
      username:
        from_secret: u_docker
      password: 
        from_secret: p_docker
      repo: ryannelson01/drone-node
      auto_tag: true
      dry_run: true #n stuff n things
    
    
 

